### ISSUE TITLE
can you provide a result file JSON format?

### ISSUE THREAD

**Issue by nicehuster** [ContinualAI/clvision-challenge-2022#10]
Are you modified the evaluation code on the server? The results submitted before were normal, but now they are wrong.
![企业微信截图_16499039258627](https://user-images.githubusercontent.com/35832232/163302968-74194968-18e1-4260-8a10-f4be2a58ae87.png)

**Comment by zhoujuncc1** [comment]
I also saw a few submissions have score 0.0002, it looks like a systematic error...
![image](https://user-images.githubusercontent.com/3220545/163314264-9c5da860-83b2-43ae-b252-8ce0350ad471.png)

**Comment by lrzpellegrini** [comment]
Hi there, I'm terribly sorry for this. The code has been recently changed to address another issue. Alas, the fix didn't work as expected. It should be fixed now. I'll remove accepted submissions with score 0.0002 so that they are not counted for the limit.

**Comment by zhoujuncc1** [comment]
It works with my submission now. Thanks for the quick fix.
