### ISSUE TITLE
can you release the metrics of  task1-task5 in leadboard?

### ISSUE THREAD

**Issue by nicehuster** [ContinualAI/clvision-challenge-2022#11]

**Comment by lrzpellegrini** [comment]
I'm afraid that CodaLab does not allow for changes to the list of reported metrics once the challenge is created.

However, you can obtain your intermediate scores by looking at the scoring output log by clicking on "View scoring output log" (see screenshot):

![image](https://user-images.githubusercontent.com/43009885/164048959-b6fc3441-7710-44f6-a211-176838014601.png)

It's a tad verbose, but it contains all intermediate scores. For detection tracks, the mAP is used (in the log it is the first element in the OrderedDict). For the classification track, the mean class accuracy is used and the updated evaluation script should also report all intermediate scores near the end of the log.

**Comment by nicehuster** [comment]
> okk, Thanks for your reply
