### ISSUE TITLE
Track3 baseline doesn't work correctly

### ISSUE THREAD

**Issue by ppppeng** [ContinualAI/clvision-challenge-2022#14]
Runned the track3 baseline, create only one json file for submit but five json files are needed for submit.

**Comment by lrzpellegrini** [comment]
Hi @ppppeng, it is possible that you are using an older version of the devkit.

Try pulling the changes from the repo or, in case you don't want to pull everything, replace the [`devkit_tools/metrics/detection_output_exporter.py`](https://github.com/ContinualAI/clvision-challenge-2022/blob/main/devkit_tools/metrics/detection_output_exporter.py) file in your codebase with the current one.
