### ISSUE TITLE
Can we add augmentation transforms to the eval transformations?

### ISSUE THREAD

**Issue by yi94code** [ContinualAI/clvision-challenge-2022#19]
We found two comments about this problem in the Challenge Repo, but their content conflicted with each other.
![image](https://user-images.githubusercontent.com/44866860/170440586-f365ef5f-28a1-43af-a5fc-eb47ece0dc23.png)
![image](https://user-images.githubusercontent.com/44866860/170440628-24072123-754f-4384-b840-b2fce8ffd84e.png)

**Comment by lrzpellegrini** [comment]
Hi @yi94code, you are free to add transformations as long as they don't introduce random behaviors.

For instance, you are free to resize or pad images, but please don't use those transformations that run based on probability.

**Comment by yi94code** [comment]
Thanks!
