### ISSUE TITLE
Detection test set all instances have "category_id": 2, "instance_id": "unlabeled"

### ISSUE THREAD

**Issue by zhoujuncc1** [ContinualAI/clvision-challenge-2022#4]
In the detection test set, `ego_objects_challenge_train.json`, all instances are of `"category_id": 2, "instance_id": "unlabeled"`

**Comment by lrzpellegrini** [comment]
Hi Zhou, that is intended. The test dataset contains no labels. The only annotations included in the test set are the bounding boxes of the main objects. Those boxes are solely used to generate the benchmark for the classification track.

**Comment by zhoujuncc1** [comment]
Hi Lorenzo,
In this case, for detection track, we will only know the score when we submit to the portal. Is it correct?
Thanks.

**Comment by lrzpellegrini** [comment]
Yes, that's correct. This is true for all tracks!

**Comment by zhoujuncc1** [comment]
Thanks for the clarification.

**Comment by miquel-espinosa** [comment]
Now that the challenge is over, is there any chance of getting the correct `category_id` for the test_set?
Thanks in advance,
