### ISSUE TITLE
What's this repo actually for?

### ISSUE THREAD

**Issue by Klawens** [ContinualAI/clvision-challenge-2022#6]
Does it mean we have to build our training and inference procedure with this repo?

**Comment by lrzpellegrini** [comment]
Hi @Klawens, that is correct. The repo contains the devkit for the [challenge](https://sites.google.com/view/clvision2022/challenge). It basically means that starting scripts (data loading + training + logging + result export) are already given for the three tracks (files `starting_template_category_detection.py`, `starting_template_instance_classification.py`, `starting_template_instance_detection.py`). However, the starting scripts implement a suboptimal solution based on a naive fine-tuning of the model. The goal is to create a solution that can learn while limiting the forgetting phenomenon. This may be a novel approach, an extension of an existing approach, a hybrid strategy, ...

The devkit is based on [Avalanche](https://github.com/ContinualAI/avalanche), which means that you can re-use the Avalanche plugins and strategies, which already implement some of the most known CL approaches. However, you are free to not use Avalanche, as long as you use the same benchmark creation function.
