### ISSUE TITLE
Why track2 demo results AP seems strange?

### ISSUE THREAD

**Issue by Millielele** [ContinualAI/clvision-challenge-2022#7]
> Eval on experience 0 (Task 0) from test stream ended.
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/AP = 0.0008
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/AP50 = 0.0014
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/AP75 = 0.0009
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/APc = -1
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/APf = 0.0008
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/APl = 0.0009
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/APm = 0.0000
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/APr = -1
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/APs = 0.0000
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/AR@300 = 0.0005
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/ARl@300 = 0.0006
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/ARm@300 = 0.0000
        LvisMetrics/eval_phase/test_stream/Task000/Exp000/bbox/ARs@300 = 0.0000
        Time_Exp/eval_phase/test_stream/Task000/Exp000 = 163.8030
-- >> End of eval phase << --
        Time_Stream/eval_phase/test_stream/Task000 = 165.282

I don't know if the AP is correct when i run starting_template_category_detection.py. Because it is so low. Hope for your reply,thanks

**Comment by zhoujuncc1** [comment]
This issue #4 may help you.

**Comment by lrzpellegrini** [comment]
Hi @Millielele, the issue may be related to the aforementioned issue.

In general, we are not planning to keep supporting the demo track. The benchmark generation procedure may be affected by some unintended behaviors, so I recommend pulling the latest version of the repo and using the non-demo benchmarks.

**Comment by Millielele** [comment]
> This issue #4 may help
Thanks

**Comment by Millielele** [comment]
> Hi @Millielele, the issue may be related to the aforementioned issue.
> 
> In general, we are not planning to keep supporting the demo track. The benchmark generation procedure may be affected by some unintended behaviors, so I recommend pulling the latest version of the repo and using the non-demo benchmarks.

Thanks，I've solved that.
