### ISSUE TITLE
mandatory metric only generate output of 1 json file for last experience

### ISSUE THREAD

**Issue by zhoujuncc1** [ContinualAI/clvision-challenge-2022#8]
For detection track, the mandatory metric output .json file with same filename. In the end, they overwrite previous outputs and only 1 `track2_output_eval_exp0.json` file is left in the output dir.
This is tested using the given `starting_template_category_detection.py`

**Comment by lrzpellegrini** [comment]
Thank you for reporting this. This is now fixed in the latest commit!
