### ISSUE TITLE
Track2 Submission Problem:  AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by Millielele** [ContinualAI/clvision-challenge-2022#9]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpYQV4mo/run/program/track2_evaluator.py", line 197, in 
    evaluate_track2(args.input_dir, args.output_dir)
  File "/tmp/codalab/tmpYQV4mo/run/program/track2_evaluator.py", line 110, in evaluate_track2
    score_str = evaluate_track2_jsons(truth_file, submit_dir)
  File "/tmp/codalab/tmpYQV4mo/run/program/track2_evaluator.py", line 49, in evaluate_track2_jsons
    predictions_json = prepare_for_ego_objects_detection(predictions_json)
  File "/tmp/codalab/tmpYQV4mo/run/program/track2_evaluator.py", line 119, in prepare_for_ego_objects_detection
    for original_id, prediction in predictions.items():
AttributeError: 'list' object has no attribute 'items'

When we tried to submit results,it said the problem like this. We check the json files and find it is list,not dict. I want to know where I can change this part code,thanks a lot.

**Comment by lrzpellegrini** [comment]
Hi @Millielele, I fixed this on the CodaLab side. Let me know if it works now!

Don't worry about failed submissions: they do not count towards the maximum number of attempts.

**Comment by Millielele** [comment]
> Hi @Millielele, I fixed this on the CodaLab side. Let me know if it works now!
> 
> Don't worry about failed submissions: they do not count towards the maximum number of attempts.

It works,thank you much
